name: NPM Package Publish

on:
  workflow_dispatch:
  release:
    types: [published]

permissions: read-all

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    uses: mauriciolauffer/.github/.github/workflows/npm-publish.yml@main
